<?php

namespace Database\Seeders;

use App\Models\DocenteMateriaGrupo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocenteMateriaGrupoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $subjects = [21,63];
        $groupsPerSubject = 4;

        for($i=21;$i<72;$i++){
            for ($j = 2; $j <= $groupsPerSubject + 1; $j++) {
                DocenteMateriaGrupo::create([
                    'teacher_id' => null,
                    'subject_id' => $i,
                    'group_id' => $j,
                ]);
            }
        }
 
        DB::table('docente_materia_grupos')->insert([
            [
                'teacher_id'=>null,
                'subject_id'=>1,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>1,
                'subject_id'=>1,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>1,
                'subject_id'=>1,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>1,
                'subject_id'=>3,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>2,
                'subject_id'=>2,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>3,
                'subject_id'=>5,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>3,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>3,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>4,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>4,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>4,
                'subject_id'=>7,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>7,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>7,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>7,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>4,
                'subject_id'=>8,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>8,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>8,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>8,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>8,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>3,
                'subject_id'=>7,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>7,
                'subject_id'=>10,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>10,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>10,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>10,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>10,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>8,
                'subject_id'=>11,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>11,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>11,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>11,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>11,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>9,
                'subject_id'=>9,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>9,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>9,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>9,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>9,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>10,
                'subject_id'=>12,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>12,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>12,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>12,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>12,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>10,
                'subject_id'=>13,
                'group_id'=>1,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>13,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>13,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>13,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>13,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>18,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>18,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>18,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>18,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>5,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>5,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>5,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>5,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>6,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>6,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>6,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>6,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>14,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>14,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>14,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>14,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>15,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>15,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>15,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>15,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>16,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>16,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>16,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>16,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>17,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>17,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>17,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>17,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>19,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>19,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>19,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>19,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>20,
                'group_id'=>2,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>20,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>20,
                'group_id'=>4,
            ],
            [
                'teacher_id'=>null,
                'subject_id'=>20,
                'group_id'=>5,
            ],
            [
                'teacher_id'=>5,
                'subject_id'=>5,
                'group_id'=>3,
            ],
            [
                'teacher_id'=>6,
                'subject_id'=>4,
                'group_id'=>3
            ],
        ]);
    }
}
